### ISSUE TITLE
Feature Request: Add all files in folder

### ISSUE THREAD

**Issue by ghost** [nulloy/nulloy#143]
Option to be able to just open the first (or any other) audio file from a folder and Nulloy automatically adds all other tracks in the folder to the playlist.

**Comment by noscript** [comment]
Have you tried "Load next file in directory" playlist option?

**Comment by megadr01d** [comment]
I did. But it just adds a track at a time. I listen to full albums and I'd like for all tracks for a particular album to show up with titles and playing times, whether I open track nr. 1 or track nr. 5 from my file manager (it's a simpler workflow than having to drag folders into Nulloy). I get a better experience from visualizing the entire album.

My feature request goes along the lines of a image viewer, for example, where you open an image and all images in the same folder get listed and you're able to change between them.

**Comment by noscript** [comment]
Sorry for no response, but the feature request makes sense. I will keep it open till it gets implemented.

**Comment by vacarogit** [comment]
the feature request makes sense. I will keep it open till it gets implemented...

Then? How's update?

**Comment by noscript** [comment]
Instead of adding another checkbox to Preferences, it would be more beneficial to improve the command line interface, so special behaviors like this one can be scripted.

To get the desired feature working in Linux, create a wrapper script with the following content:

```sh
#!/usr/bin/env bash

dir=$(dirname "$1")
files=("$dir"/*)
nulloy "${files[@]}" &
```

Make it executable:
```sh
chmod +x ~/nulloy-directory-mode.sh
```

Then you can use the wrapper like so:
```sh
~/nulloy-directory-mode.sh "/path/to/some file.mp3"
```
and it will collect all the files in the directory and pass them to Nulloy. If you don't want to preserve the files in the playlist, uncheck "Enqueue files" option in Preferences.

You can associate your media with the wrapper using your file manager. If you don't know how to do it or need more help with e.g. Windows or macOS, please let me know.
