### ISSUE TITLE
Temporary files are not deleted

### ISSUE THREAD

**Issue by KL7000F** [nulloy/nulloy#221]
When I play songs from a network drive (NAS), temporary files are created. However, these are **not deleted** after closing the player. After playing several times, the directory becomes fuller and fuller with these files.

![image](https://github.com/nulloy/nulloy/assets/16374462/16481dc5-fbdb-42b2-973f-15a97f8a413b)
![image](https://github.com/nulloy/nulloy/assets/16374462/e33ab38f-810d-4565-81b1-2e8daca7f2c8)
[N1QD26~1.ZIP](https://github.com/nulloy/nulloy/files/12438019/N1QD26.1.ZIP)

**Comment by noscript** [comment]
Those were GStreamer plugins registry temporal files that GStreamer failed to move/rename. I tried to avoid creating the registry by writing it to `NUL` special file. Apparently GStreamer does not recognize `NUL` and it tried to create a real file which that name, failed every time and did not clean up. That's actually a bug in GStreamer.

It turns out that having the registry stored on disk actually speeds up GStreamer initialization, and thus speeds up Nulloy start up. I changed it in 2c815ae so the registry will be stored in `%APPDATA%/Nulloy` which will be removed when you uninstall Nulloy.

Expect the fix in the next release.
