### ISSUE TITLE
Use system qxt libraries (was Bundled libraries)

### ISSUE THREAD

**Issue by cicku** [nulloy/nulloy#34]
Hi,

I found 3 3rd party libraries bundled in your project. I'm concerned about the qxt, why not use 0.6.2 instead of 0.6.1(reduced?)?

Other 2 libraries are easy to unbundle by myself.

Thanks.

**Comment by noscript** [comment]
[The official page](http://dev.libqxt.org/libqxt/wiki/Home) says:

> LIBQXT IS NO LONGER MAINTAINED
Qxt will likely not work with newer Qt versions due to usage of internal api. We recommend that you pick out the parts you want instead of using the entire libqxt.

It's very likely the library will disappear from repositories soon. So I better keep it bundled with Nulloy source.
