### ISSUE TITLE
WAV "Error: The autoaudiosink element is missing."

### ISSUE THREAD

**Issue by dzg** [nulloy/nulloy#70]
Just installed 0.8 on OSX 10.10.

Any WAV file I try to open gives me 
"Error: The autoaudiosink element is missing."

What does this mean?

**Comment by noscript** [comment]
Hm, that's new. Not sure why it wants the autoaudiosink element, I will check.

**Comment by dzg** [comment]
MP3, AIFF work great ... Just issues with WAV. Tried many sources, all give that error. THanks!

**Comment by noscript** [comment]
Could you please post a small sample of the file?

**Comment by dzg** [comment]
Here: https://dl.dropboxusercontent.com/u/19453/%2064A1DEMO.wav

**Comment by noscript** [comment]
Unfortunately I couldn’t reproduce the problem on 10.10.4. I will make a separate build which includes the autoaudiosink element, let's see if makes any difference.

**Comment by noscript** [comment]
Ok, please try this version https://github.com/nulloy/nulloy/releases/download/0.8-autosink-fix/Nulloy-0.8-autosink-fix-universal.dmg

**Comment by gonzzza007** [comment]
Hi there, not sure if i have to open another case or not. I had this error for ages and couldn't fix it no matter what. Mac OSX 10.10.5 at the moment. Unfortunately in my case - i cannot play any file format... I have installed your "autosink-fix" version and now i get these errors:
1) WAV: Error: Internal data flow error.
2) MP3: GStreamer encountered a general stream error.

I have a standard installation of OSX, the only thing i can think of is that i ws messing with Python Framework (i installed a new version and tried to replace OSX's system one). But i have removed it later and everything else seemes to work. I also tried to reinstall /update GStreamew using brew - but no use. Also i tried to install Nulloy using "brew cask install nulloy" hoping it will fix all needed dependencies - but no luck also.

I will provide you any needed information. I believe the music files are not the issue here - these are the same files that played well before.

Love nulloy. There's really no replacement for a player with a nice waveform view and no fancy but not needed features.

**Comment by noscript** [comment]
I suppose you are using some external USB sound card? GStreamer 1.0 doesn't work with those. I think the previous version [Nulloy-0.7.5.dmg](https://github.com/nulloy/nulloy/releases/download/0.7.5/Nulloy-0.7.5.dmg) will work for you, as it comes with the older version of GStreamer.

If that works, please let me know what your sound card is.

**Comment by gonzzza007** [comment]
I have a MOTU Ultralite MK3, its FireWire. I tried 0.7.5 - unfortunately it still doesn't work with my card, but works great with MacBook internal card. 

Does Gstreamer come somehow bundled in Nulloy or it is used from the system? Then I hopefully can downgrade it...

**Comment by noscript** [comment]
GStreamer1.0 is a major upgrade from GStreamer0.10, they are not compatible on API level. And since Nulloy 0.7.5 doesn't work for you either - no point.

So far the list of problematic sound cards:
* MOTU Ultralite MK3 (FireWire)
* MOTU 896mk3 Hybrid (FireWire / USB)
* RME Fireface 400 (FireWire)
* AVID Mbox 2 Pro (USB)
* Steinberg MR816X (FireWire)
* Lynx L22 (PCI)

**Comment by gonzzza007** [comment]
Haha, so I'm the lucky one! Well, at least i can use Nulloy when I'm not on Motu. Thanks!
